### ISSUE TITLE
Symfony3 deprecation message

### ISSUE THREAD

**Issue by Gemineye** [lexik/LexikMonologBrowserBundle#11]
Hi,

i think this would be a very small change?

The "pattern" option in file ".../vendor/lexik/monolog-browser-bundle/Lexik/Bundle/MonologBrowserBundle/Resources/config/routing.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.

**Comment by cedric-g** [comment]
Hi, I've updated the code.

**Comment by Gemineye** [comment]
Great! Could you also create a new Tag?

**Comment by shieldo** [comment]
A new release tag for this would be good!

**Comment by sdieunidou** [comment]
A new release tag was added
