### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by marcusfritze** [lexik/LexikMonologBrowserBundle#17]
Is it planned to support Symfony 3?

**Comment by sdieunidou** [comment]
Bundle is now deprecated
Pull request #20 exist, maybe we can merge it, but need code review

**Comment by roldan** [comment]
Hi @sdieunidou, 

are you planning merge Pull request #20 ? Maybe to some branch 3.x?

Thanks,
Matías

**Comment by gilles-g** [comment]
Hi,

As it's mentioned in the readme : https://github.com/lexik/LexikMonologBrowserBundle#this-bundle-is-deprecated

You should use an other service like graylog or sentry!

**Comment by sdieunidou** [comment]
@spike31 Tu peux ajouter le flag sur packagist ( https://packagist.org/packages/lexik/workflow-bundle ) en cliquant sur "Abandon".

Les utilisateurs auront le message lors de l'update composer: https://www.tomasvotruba.cz/assets/images/posts/2017/deprecate/composer-info.png

**Comment by gilles-g** [comment]
Ah ouais merci :) !

**Comment by roldan** [comment]
Thanks guys!
